### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by lars-w-pedersen** [Geta/geta-optimizely-extensions#11]
after i installed this package i got this error on startup:

System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'EPiServer.Shell.Navigation.Internal.NavigationOptions' from assembly 'EPiServer.Shell, Version=12.0.1.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7'.
  Source=EPiServer.Cms.AspNetCore.Migration
  StackTrace:
   at EPiServer.Shell.ShellConfigurationInitialization.ConfigureContainer(ServiceConfigurationContext context)
   at EPiServer.Framework.Initialization.Internal.ModuleNode.<>c__DisplayClass4_0.<ConfigureContainer>b__0()
   at EPiServer.Framework.Initialization.Internal.ModuleNode.Execute(Action a, String key)
   at EPiServer.Framework.Initialization.Internal.ModuleNode.ConfigureContainer(ServiceConfigurationContext context)
   at EPiServer.Framework.Initialization.InitializationEngine.ConfigureCurrentModules(Boolean final)
   at EPiServer.Framework.Initialization.InitializationEngine.ConfigureModules(IEnumerable`1 modules)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddCmsHost(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddCms(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddCommerce(IServiceCollection services)
   at Valtech.Kb.Cms.Startup.ConfigureServices(IServiceCollection services) in C:\Projects\KB\Webprogram\Valtech.Kb.Cms\Startup.cs:line 80

**Comment by marisks** [comment]
Should be fixed
